using UnityEngine;
using UnityEngine.SceneManagement;

public class CollisionHandler : MonoBehaviour
{
    [SerializeField] float levelLoadDelay = 2f;
   void OnCollisionEnter(Collision other) 
   {
        switch (other.gameObject.tag)
        {
            case "Friendly":
                Debug.Log("This thing is friendly");
                break;
            case "Finish":
                StartSuccessSequence();
                break;    
            case "Fuel":
                Debug.Log("You picked up fuel.");
                break;
            default:
                //StartCrashSequence();
                break;
        } 
    
   }

    void StartSuccessSequence()
    {
       GetComponent<Movement>().enabled = false;
       Invoke("LoadNextLevel", levelLoadDelay); 
    }
   void StartCrashSequence()
   {
        // to do add sfx upon crash
        // to do add particle effect upon crash
        GetComponent<Movement>().enabled = false;
        Invoke("ReloadLevel", levelLoadDelay);
   }
   void LoadNextLevel()
   {
        int currentSceneIndex = SceneManager.GetActiveScene().buildIndex;
        int nextSceneIndex = currentSceneIndex + 1;
        if (nextSceneIndex == SceneManager.sceneCountInBuildSettings)
        {
            nextSceneIndex = 0;
        }
        SceneManager.LoadScene(nextSceneIndex);
   }
   void ReloadLevel()
   {
        int currentSceneIndex = SceneManager.GetActiveScene().buildIndex;
        SceneManager.LoadScene(currentSceneIndex);
   }
}
